import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="bg-background text-on-background">
        <aside className="h-screen w-64 fixed left-0 top-0 border-r border-slate-200 bg-slate-50 hidden md:flex flex-col p-4 space-y-2">
          <div className="mb-8 px-2 flex items-center gap-3">
            <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center text-white">
              <span
                className="material-symbols-outlined"
                data-icon="link"
                data-weight="fill"
              >
                link
              </span>
            </div>
            <div>
              <h1 className="text-xl font-black text-blue-600 leading-tight">
                LinkSwift Pro
              </h1>
              <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">
                Enterprise Plan
              </p>
            </div>
          </div>
          <button className="w-full py-3 px-4 bg-blue-600 text-white rounded-lg font-semibold text-sm flex items-center justify-center gap-2 mb-6 hover:bg-blue-700 transition-all">
            <span className="material-symbols-outlined text-sm" data-icon="add">
              add
            </span>
            Create New Link
          </button>
          <nav className="flex-1 space-y-1">
            <a
              className="flex items-center gap-3 px-4 py-3 bg-blue-50 text-blue-600 rounded-lg font-semibold text-sm"
              href="#"
            >
              <span className="material-symbols-outlined" data-icon="dashboard">
                dashboard
              </span>
              Dashboard
            </a>
            <a
              className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-100 rounded-lg transition-all font-semibold text-sm"
              href="#"
            >
              <span
                className="material-symbols-outlined"
                data-icon="query_stats"
              >
                query_stats
              </span>
              Analytics
            </a>
            <a
              className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-100 rounded-lg transition-all font-semibold text-sm"
              href="#"
            >
              <span className="material-symbols-outlined" data-icon="link">
                link
              </span>
              Links
            </a>
            <a
              className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-100 rounded-lg transition-all font-semibold text-sm"
              href="#"
            >
              <span className="material-symbols-outlined" data-icon="settings">
                settings
              </span>
              Settings
            </a>
          </nav>
          <div className="pt-4 border-t border-slate-200 space-y-1">
            <a
              className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-100 rounded-lg transition-all font-semibold text-sm"
              href="#"
            >
              <span className="material-symbols-outlined" data-icon="help">
                help
              </span>
              Help Center
            </a>
            <a
              className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-100 rounded-lg transition-all font-semibold text-sm"
              href="#"
            >
              <span className="material-symbols-outlined" data-icon="logout">
                logout
              </span>
              Logout
            </a>
          </div>
        </aside>
        <main className="md:ml-64 min-h-screen p-8 lg:p-12">
          <header className="flex justify-between items-center mb-10">
            <div>
              <h2 className="text-headline-lg font-headline-lg text-on-surface">
                Welcome back, Alex
              </h2>
              <p className="text-body-md text-on-secondary-container mt-1">
                Here's what's happening with your links today.
              </p>
            </div>
            <div className="flex items-center gap-4">
              <button className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center border border-slate-200">
                <span
                  className="material-symbols-outlined text-slate-600"
                  data-icon="notifications"
                >
                  notifications
                </span>
              </button>
              <img
                alt="User Profile Avatar"
                className="w-10 h-10 rounded-full border-2 border-white shadow-md"
                data-alt="A high-quality studio headshot of a professional user with a friendly expression. The lighting is bright and even, casting soft shadows against a neutral, minimalist gray background. The aesthetic is clean and modern, perfectly complementing a high-end enterprise software dashboard. The user has dark hair and is wearing a simple black turtleneck."
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuDcjvvJIf6wfcgPvMny-eOmxF-10QHxfKUDqJ9V0dl7I9m8pS26doENFzrE4WmsbpBfgfun3xNN4kaROtA0Vk-nIFfTSA2lfmCVsSDB3ez5NFoSCYkVRDNIDBenvLsFJzIInU6Npfxc59njs5NeE6Bp19CQaDSY6bX0oq2u-khFiuOgVi16SRf5yNTVkxznAqT7cNFQoediHZ7Hfd4nwHF72XnsGrESMvWDii1oLcFCpacD8A6AdlE8Rh4LmRLWmOFd6DCAWDI9iwLL"
              />
            </div>
          </header>
          <section className="mb-10">
            <div className="bg-white rounded-2xl p-8 shadow-[0_4px_12px_rgba(0,0,0,0.05)] border border-slate-100">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-8 h-8 bg-primary-fixed flex items-center justify-center rounded-lg text-primary">
                  <span
                    className="material-symbols-outlined text-sm"
                    data-icon="auto_fix_high"
                  >
                    auto_fix_high
                  </span>
                </div>
                <h3 className="text-headline-sm font-headline-sm text-on-surface">
                  Shorten a new link
                </h3>
              </div>
              <div className="flex flex-col md:flex-row gap-4">
                <div className="flex-1 relative">
                  <span
                    className="absolute left-4 top-1/2 -translate-y-1/2 material-symbols-outlined text-slate-400"
                    data-icon="link"
                  >
                    link
                  </span>
                  <input
                    className="w-full pl-12 pr-4 py-4 bg-slate-50 border border-slate-200 rounded-xl text-body-md focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600 outline-none transition-all"
                    placeholder="Paste your long URL here (e.g. https://very-long-product-page-url.com/...)"
                    type="text"
                  />
                </div>
                <button className="px-8 py-4 bg-primary text-white font-bold rounded-xl hover:shadow-lg active:scale-95 transition-all flex items-center justify-center gap-2">
                  Shorten Now
                  <span
                    className="material-symbols-outlined"
                    data-icon="arrow_forward"
                  >
                    arrow_forward
                  </span>
                </button>
              </div>
            </div>
          </section>
          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">
            <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
              <div className="flex justify-between items-start mb-4">
                <span
                  className="p-2 bg-blue-50 text-blue-600 rounded-lg material-symbols-outlined"
                  data-icon="ads_click"
                >
                  ads_click
                </span>
                <span className="text-label-md text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">
                  +12.5%
                </span>
              </div>
              <p className="text-label-lg text-slate-500">Total Clicks</p>
              <h4 className="text-headline-md font-headline-md text-on-surface mt-1">
                42,892
              </h4>
            </div>
            <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
              <div className="flex justify-between items-start mb-4">
                <span
                  className="p-2 bg-purple-50 text-purple-600 rounded-lg material-symbols-outlined"
                  data-icon="link"
                >
                  link
                </span>
                <span className="text-label-md text-slate-400 bg-slate-50 px-2 py-1 rounded-full">
                  Static
                </span>
              </div>
              <p className="text-label-lg text-slate-500">Active Links</p>
              <h4 className="text-headline-md font-headline-md text-on-surface mt-1">
                1,204
              </h4>
            </div>
            <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
              <div className="flex justify-between items-start mb-4">
                <span
                  className="p-2 bg-orange-50 text-orange-600 rounded-lg material-symbols-outlined"
                  data-icon="group"
                >
                  group
                </span>
                <span className="text-label-md text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">
                  +4.2%
                </span>
              </div>
              <p className="text-label-lg text-slate-500">Unique Visitors</p>
              <h4 className="text-headline-md font-headline-md text-on-surface mt-1">
                18,502
              </h4>
            </div>
            <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
              <div className="flex justify-between items-start mb-4">
                <span
                  className="p-2 bg-emerald-50 text-emerald-600 rounded-lg material-symbols-outlined"
                  data-icon="speed"
                >
                  speed
                </span>
                <span className="text-label-md text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">
                  Optimal
                </span>
              </div>
              <p className="text-label-lg text-slate-500">Avg. Load Time</p>
              <h4 className="text-headline-md font-headline-md text-on-surface mt-1">
                142ms
              </h4>
            </div>
          </section>
          <section className="bg-white rounded-2xl shadow-[0_4px_12px_rgba(0,0,0,0.05)] border border-slate-100 overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-50 flex justify-between items-center">
              <h3 className="text-headline-sm font-headline-sm text-on-surface">
                Your Recent Links
              </h3>
              <button className="text-primary font-bold text-sm hover:underline">
                View All
              </button>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-slate-50 text-left">
                  <tr>
                    <th className="px-8 py-4 text-label-md text-slate-500 uppercase tracking-wider">
                      Short Link
                    </th>
                    <th className="px-8 py-4 text-label-md text-slate-500 uppercase tracking-wider">
                      Original Destination
                    </th>
                    <th className="px-8 py-4 text-label-md text-slate-500 uppercase tracking-wider">
                      Clicks
                    </th>
                    <th className="px-8 py-4 text-label-md text-slate-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-8 py-4 text-label-md text-slate-500 uppercase tracking-wider text-right">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  <tr className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-8 py-5">
                      <span className="font-bold text-blue-600 text-body-md">
                        lswift.co/spring-sale-24
                      </span>
                    </td>
                    <td className="px-8 py-5 max-w-xs overflow-hidden">
                      <p className="text-body-md text-slate-500 truncate">
                        https://store.brandname.com/campaigns/spring-2024/flash-sale?ref=dash
                      </p>
                    </td>
                    <td className="px-8 py-5">
                      <span className="text-body-md font-semibold text-on-surface">
                        1,248
                      </span>
                    </td>
                    <td className="px-8 py-5">
                      <span className="bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
                        Active
                      </span>
                    </td>
                    <td className="px-8 py-5 text-right space-x-2">
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Copy"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="content_copy"
                        >
                          content_copy
                        </span>
                      </button>
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Analytics"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="bar_chart"
                        >
                          bar_chart
                        </span>
                      </button>
                    </td>
                  </tr>
                  <tr className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-8 py-5">
                      <span className="font-bold text-blue-600 text-body-md">
                        lswift.co/product-launch
                      </span>
                    </td>
                    <td className="px-8 py-5 max-w-xs overflow-hidden">
                      <p className="text-body-md text-slate-500 truncate">
                        https://brandname.com/new-product-pre-order-page-long-string
                      </p>
                    </td>
                    <td className="px-8 py-5">
                      <span className="text-body-md font-semibold text-on-surface">
                        892
                      </span>
                    </td>
                    <td className="px-8 py-5">
                      <span className="bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
                        Active
                      </span>
                    </td>
                    <td className="px-8 py-5 text-right space-x-2">
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Copy"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="content_copy"
                        >
                          content_copy
                        </span>
                      </button>
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Analytics"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="bar_chart"
                        >
                          bar_chart
                        </span>
                      </button>
                    </td>
                  </tr>
                  <tr className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-8 py-5">
                      <span className="font-bold text-blue-600 text-body-md">
                        lswift.co/winter-recap
                      </span>
                    </td>
                    <td className="px-8 py-5 max-w-xs overflow-hidden">
                      <p className="text-body-md text-slate-500 truncate">
                        https://blog.brandname.com/posts/2023/winter-season-wrap-up-report
                      </p>
                    </td>
                    <td className="px-8 py-5">
                      <span className="text-body-md font-semibold text-on-surface">
                        4,521
                      </span>
                    </td>
                    <td className="px-8 py-5">
                      <span className="bg-slate-100 text-slate-500 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
                        Expired
                      </span>
                    </td>
                    <td className="px-8 py-5 text-right space-x-2">
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Copy"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="content_copy"
                        >
                          content_copy
                        </span>
                      </button>
                      <button
                        className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                        title="Analytics"
                      >
                        <span
                          className="material-symbols-outlined text-sm"
                          data-icon="bar_chart"
                        >
                          bar_chart
                        </span>
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>
        </main>
        <button className="fixed bottom-8 right-8 w-16 h-16 bg-primary text-white rounded-full shadow-2xl flex items-center justify-center hover:scale-110 active:scale-95 transition-all z-50">
          <span className="material-symbols-outlined text-3xl" data-icon="add">
            add
          </span>
        </button>
        <nav className="md:hidden fixed bottom-0 left-0 w-full h-16 flex justify-around items-center px-4 pb-safe bg-white border-t border-slate-200 z-50">
          <a
            className="flex flex-col items-center justify-center text-blue-600 py-1"
            href="#"
          >
            <span
              className="material-symbols-outlined"
              data-icon="home"
              data-weight="fill"
            >
              home
            </span>
            <span className="text-[10px] font-bold uppercase tracking-widest mt-1">
              Home
            </span>
          </a>
          <a
            className="flex flex-col items-center justify-center text-slate-400 py-1"
            href="#"
          >
            <span className="material-symbols-outlined" data-icon="insights">
              insights
            </span>
            <span className="text-[10px] font-bold uppercase tracking-widest mt-1">
              Stats
            </span>
          </a>
          <a
            className="flex flex-col items-center justify-center text-slate-400 py-1"
            href="#"
          >
            <span className="material-symbols-outlined" data-icon="list">
              list
            </span>
            <span className="text-[10px] font-bold uppercase tracking-widest mt-1">
              Links
            </span>
          </a>
          <a
            className="flex flex-col items-center justify-center text-slate-400 py-1"
            href="#"
          >
            <span className="material-symbols-outlined" data-icon="person">
              person
            </span>
            <span className="text-[10px] font-bold uppercase tracking-widest mt-1">
              Account
            </span>
          </a>
        </nav>
        <footer className="md:ml-64 w-full py-12 mt-20 border-t border-slate-100 bg-slate-50">
          <div className="mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="font-plus-jakarta text-xs text-slate-500">
              © 2024 LinkSwift Technologies Inc. All rights reserved.
            </p>
            <div className="flex gap-6">
              <a
                className="text-xs text-slate-500 hover:text-blue-600 transition-colors"
                href="#"
              >
                Privacy Policy
              </a>
              <a
                className="text-xs text-slate-500 hover:text-blue-600 transition-colors"
                href="#"
              >
                Terms of Service
              </a>
              <a
                className="text-xs text-slate-500 hover:text-blue-600 transition-colors"
                href="#"
              >
                Status
              </a>
              <a
                className="text-xs text-slate-500 hover:text-blue-600 transition-colors"
                href="#"
              >
                Security
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
